baseurl = "https://flowerinthenight.com"
copyright = "© Flowerinthenight, 2016-2024. All rights reserved."
enablerobotstxt = true
languagecode = "en-us"
paginate = 10000
timezone = "Asia/Tokyo"
titlecasestyle = "Go"

[services]
  [services.googleAnalytics]
    ID = 'G-EZWHM5C9YT'

[languages.en]
title = "flowerinthenight"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "content"
name = "Blog"
url = "/blog/"
weight = 20

[[languages.en.menu.main]]
identifier = "bookshelf"
name = "Bookshelf"
url = "/bookshelf/"
weight = 30

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 90

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "paige-search", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[paige.analytics]
disable = false

[params.paige]
site_title = "f14t"
site_description = ""
style = "#paige-content > * { margin-left: auto; margin-right: auto; max-width: 60rem; }"

[[params.paige.feed.atom.authors]]
email = "root@flowerinthenight.com"
name = "Flowerinthenight"
url = "https://flowerinthenight.com"

[params.paige.feed.rss]
managing_editor = "root@flowerinthenight.com (Flowerinthenight)"
web_master = "root@flowerinthenight.com (Flowerinthenight)"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
