[services]
  [services.googleAnalytics]
    ID = 'G-333404550'

baseurl = "https://example.com"
copyright = "© Flowerinthenight, 2016-2024. All rights reserved."
enablerobotstxt = true
languagecode = "en-us"
paginate = 10000
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

[languages.en]
title = "flowerinthenight"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "content"
name = "Blog"
url = "/blog/"
weight = 20

[[languages.en.menu.main]]
identifier = "bookshelf"
name = "Bookshelf"
url = "/bookshelf/"
weight = 30

# [[languages.en.menu.main]]
# identifier = "shortcodes"
# name = "Shortcodes"
# url = "/shortcodes/"
# weight = 40

# [[languages.en.menu.main]]
# identifier = "customization"
# name = "Customization"
# url = "/customization/"
# weight = 50

# [[languages.en.menu.main]]
# identifier = "authors"
# name = "Authors"
# url = "/authors/"
# weight = 60

# [[languages.en.menu.main]]
# identifier = "series"
# name = "Series"
# url = "/series/"
# weight = 70

# [[languages.en.menu.main]]
# identifier = "categories"
# name = "Categories"
# url = "/categories/"
# weight = 80

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 90

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "paige-search", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.paige]
site_title = "f/t"
site_description = ""
style = "#paige-content > * { margin-left: auto; margin-right: auto; max-width: 60rem; }"
# file_edit_url = "https://github.com/willfaught/paige/edit/master/exampleSite/content/%s"
# file_history_url = "https://github.com/willfaught/paige/commits/master/exampleSite/content/%s"

[[params.paige.feed.atom.authors]]
email = "example@example.com"
name = "John Doe"
url = "https://example.com"

[params.paige.feed.rss]
managing_editor = "example@example.com (John Doe)"
web_master = "example@example.com (John Doe)"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
